

@token = {{$dotenv TICKTICK_ACCESS_TOKEN}}
@base_url ={{$dotenv TICKTICK_BASE_URL}}/focus
@focus_id = focus-1

### Get focus by focus id
GET {{base_url}}/{{focus_id}}?type=0
Authorization: Bearer {{token}}

### Get focuses by time range
GET {{base_url}}?from=2026-04-01T00:00:00+0800&to=2026-04-02T00:00:00+0800&type=1
Authorization: Bearer {{token}}

### Delete focus
DELETE {{base_url}}/{{focus_id}}?type=0
Authorization: Bearer {{token}}
